[build]
  command = "cd frontend && npm ci --include=dev && npm run build"
  publish = "frontend/dist"
  functions = "backend/netlify/functions"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Language = ["en"] }
