const now = Date.now();

const hoursAgo = (hours) => new Date(now - hours * 60 * 60 * 1000).toISOString();
const daysAgo = (days, hour = 10) => {
  const date = new Date(now - days * 24 * 60 * 60 * 1000);
  date.setHours(hour, 15, 0, 0);
  return date.toISOString();
};

export const dummyDashboardRecords = [
  {
    id: "HFB-2026-401",
    patientName: "Ritika Nair",
    patientEmail: "ritika@example.com",
    service: "Doctor",
    services: ["Doctor"],
    positiveTags: ["Professional", "Quick diagnosis"],
    negativeTags: [],
    sentimentLabel: "Positive",
    sentiment: "positive",
    comment: "Doctor explained everything clearly and made the visit stress-free.",
    createdAt: hoursAgo(2),
    status: "COMPLETED",
  },
  {
    id: "HFB-2026-402",
    patientName: "Aarav Sharma",
    patientEmail: "aarav@example.com",
    service: "Parking",
    services: ["Parking"],
    positiveTags: [],
    negativeTags: ["Long wait", "No guidance"],
    sentimentLabel: "Negative",
    sentiment: "negative",
    comment: "Parking area was full and staff did not direct us to alternate slots.",
    createdAt: hoursAgo(4),
    status: "Pending",
  },
  {
    id: "HFB-2026-403",
    patientName: "Meera Joseph",
    patientEmail: "meera@example.com",
    service: "Pharmacy",
    services: ["Pharmacy"],
    positiveTags: ["Fast service", "Medicine available"],
    negativeTags: [],
    sentimentLabel: "Positive",
    sentiment: "positive",
    comment: "Prescription was ready quickly and the counter staff were helpful.",
    createdAt: hoursAgo(6),
    status: "IN PROGRESS",
  },
  {
    id: "HFB-2026-404",
    patientName: "Arjun Patel",
    patientEmail: "arjun@example.com",
    service: "Facilities",
    services: ["Facilities"],
    positiveTags: [],
    negativeTags: ["Cleanliness", "Restroom issue"],
    sentimentLabel: "Negative",
    sentiment: "negative",
    comment: "Restroom near the lobby needed immediate cleaning.",
    createdAt: hoursAgo(8),
    status: "Pending",
  },
  {
    id: "HFB-2026-405",
    patientName: "Sana Khan",
    patientEmail: "sana@example.com",
    service: "Doctor",
    services: ["Doctor"],
    positiveTags: ["Good explanation"],
    negativeTags: ["Long wait time"],
    sentimentLabel: "Mixed",
    sentiment: "mixed",
    comment: "The consultation quality was good, but the wait was too long.",
    createdAt: daysAgo(1, 14),
    status: "IN PROGRESS",
  },
  {
    id: "HFB-2026-406",
    patientName: "Nikhil Rao",
    patientEmail: "nikhil@example.com",
    service: "Garden",
    services: ["Garden"],
    positiveTags: ["Clean area"],
    negativeTags: [],
    sentimentLabel: "Positive",
    sentiment: "positive",
    comment: "The garden and walkways were clean and pleasant.",
    createdAt: daysAgo(2, 11),
    status: "COMPLETED",
  },
  {
    id: "HFB-2026-407",
    patientName: "Priya Das",
    patientEmail: "priya@example.com",
    service: "Facilities",
    services: ["Facilities"],
    positiveTags: ["Helpful cleaner"],
    negativeTags: ["Broken sink"],
    sentimentLabel: "Mixed",
    sentiment: "mixed",
    comment: "Staff was helpful but a sink in the washroom was broken.",
    createdAt: daysAgo(3, 12),
    status: "Pending",
  },
  {
    id: "HFB-2026-408",
    patientName: "Karan Verma",
    patientEmail: "karan@example.com",
    service: "Parking",
    services: ["Parking"],
    positiveTags: [],
    negativeTags: ["No slot available"],
    sentimentLabel: "Negative",
    sentiment: "negative",
    comment: "We had to circle around for 20 minutes before finding a slot.",
    createdAt: daysAgo(5, 9),
    status: "Pending",
  },
];

export const dummyComparisonRecords = [
  {
    id: "HFB-2026-301",
    patientName: "Devika Menon",
    patientEmail: "devika@example.com",
    service: "Doctor",
    services: ["Doctor"],
    positiveTags: ["Friendly doctor"],
    negativeTags: [],
    sentimentLabel: "Positive",
    sentiment: "positive",
    comment: "Friendly interaction and proper guidance.",
    createdAt: daysAgo(8, 10),
    status: "COMPLETED",
  },
  {
    id: "HFB-2026-302",
    patientName: "Rohan Gupta",
    patientEmail: "rohan@example.com",
    service: "Parking",
    services: ["Parking"],
    positiveTags: [],
    negativeTags: ["No security"],
    sentimentLabel: "Negative",
    sentiment: "negative",
    comment: "Parking felt unmanaged and unsafe late in the evening.",
    createdAt: daysAgo(9, 17),
    status: "Pending",
  },
  {
    id: "HFB-2026-303",
    patientName: "Anita Roy",
    patientEmail: "anita@example.com",
    service: "Facilities",
    services: ["Facilities"],
    positiveTags: ["Clean corridor"],
    negativeTags: [],
    sentimentLabel: "Positive",
    sentiment: "positive",
    comment: "The general waiting area was neat and well kept.",
    createdAt: daysAgo(10, 13),
    status: "COMPLETED",
  },
];
